language: python
python:
        - 3.6
before_install:
        - python --version
        - pip install -U pip
        - pip install -U pytest
        - pip instal codecov
install:
        - pip install ".[test]" .
script: pytest
after_success:
        - codecov

